### ISSUE TITLE
Prints only once when the app starts

### ISSUE THREAD

**Issue by nyugoh** [andrey-ushakov/esc_pos_bluetooth#30]
I can only be able to print once, only when the app starts for the first time, subsequent attempts to print am getting _Printer connection timeout_
 Here are the logs.
```
D/BluetoothBasicPlugin(31167): start scan 
D/BluetoothAdapter(31167): STATE_ON
I/chatty  (31167): uid=10277(ke.co.quebasetech.wanga_admin) identical 1 line
D/BluetoothAdapter(31167): STATE_ON
D/BluetoothLeScanner(31167): Start Scan with callback
D/BluetoothLeScanner(31167): onScannerRegistered() - status=0 scannerId=9 mScannerId=0
D/BluetoothAdapter(31167): STATE_ON
D/BluetoothAdapter(31167): STATE_ON
D/BluetoothLeScanner(31167): Stop Scan with callback
D/BluetoothAdapter(31167): STATE_ON
D/BluetoothAdapter(31167): STATE_ON
D/BluetoothLeScanner(31167): could not find callback wrapper
D/BluetoothSocket(31167): close() this: android.bluetooth.BluetoothSocket@2173db5, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@7b09c4a, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@10d47bbmSocket: android.net.LocalSocket@424b4d8 impl:android.net.LocalSocketImpl@9cb0031 fd:java.io.FileDescriptor@c643316, mSocketState: CONNECTED
W/System.err(31167): java.io.IOException: bt socket closed, read return: -1
D/BluetoothSocket(31167): close() this: android.bluetooth.BluetoothSocket@2173db5, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@7b09c4a, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@10d47bbmSocket: null, mSocketState: CLOSED
D/BluetoothSocket(31167): close() this: android.bluetooth.BluetoothSocket@2173db5, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@7b09c4a, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@10d47bbmSocket: null, mSocketState: CLOSED
W/System.err(31167): 	at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:721)
W/System.err(31167): 	at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:88)
W/System.err(31167): 	at java.io.InputStream.read(InputStream.java:101)
W/System.err(31167): 	at com.gprinter.io.BluetoothPort.readData(BluetoothPort.java:130)
W/System.err(31167): 	at com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager.readDataImmediately(DeviceConnFactoryManager.java:418)
W/System.err(31167): 	at com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager$PrinterReader.run(DeviceConnFactoryManager.java:498)
E/BluetoothPort(31167): connection device is lost
E/DeviceConnFactoryManager(31167):  read 0
D/BluetoothAdapter(31167): cancelDiscovery
D/BluetoothAdapter(31167): cancelDiscovery = true
D/BluetoothUtils(31167): isSocketAllowedBySecurityPolicy start : device null
W/BluetoothAdapter(31167): getBluetoothService() called with no BluetoothManagerCallback
E/DeviceConnFactoryManager(31167): wait read 
E/BluetoothPort(31167): read length1
E/DeviceConnFactoryManager(31167):  read 1
E/DeviceConnFactoryManager(31167): wait read 
I/flutter (31167): Error. Printer connection timeout
```

**Comment by c0c4i** [comment]
@nyugoh did you solve it?

**Comment by DhavalRKansara** [comment]
@nyugoh any update on how you fixed it?

**Comment by farhan-syah** [comment]
I am having the same issue.
