### ISSUE TITLE
can not pair with HM-A300 printer

### ISSUE THREAD

**Issue by drunisa007** [andrey-ushakov/esc_pos_bluetooth#45]
W/BluetoothAdapter(23880): getBluetoothService() called with no BluetoothManagerCallback
D/BluetoothBasicPlugin(23880): stateStreamHandler, current action: android.bluetooth.device.action.ACL_CONNECTED
E/flutter (20762): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Future already completed
E/flutter (20762): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
E/flutter (20762): #1      PrinterBluetoothManager.writeBytes.<anonymous closure> (package:esc_pos_bluetooth/src/printer_bluetooth_manager.dart:117:23)
E/flutter (20762): <asynchronous suspension>
E/flutter (20762): #2      PrinterBluetoothManager.writeBytes.<anonymous closure> (package:esc_pos_bluetooth/src/printer_bluetooth_manager.dart)
E/flutter (20762): #3      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (20762): #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (20762): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (20762): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (20762): #7      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (20762): #8      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (20762): #9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (20762): #10     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (20762): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (20762): #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (20762): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (20762): #14     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (20762): #15     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (20762): #16     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (20762): #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (20762): #18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (20762): #19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (20762): 
E/MethodChannel#flutter_bluetooth_basic/methods(23880): Failed to handle method call
E/MethodChannel#flutter_bluetooth_basic/methods(23880): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager$PrinterReader.cancel()' on a null object reference
E/MethodChannel#flutter_bluetooth_basic/methods(23880): 	at com.tablemi.flutter_bluetooth_basic.FlutterBluetoothBasicPlugin.disconnect(FlutterBluetoothBasicPlugin.java:250)
E/MethodChannel#flutter_bluetooth_basic/methods(23880): 	at com.tablemi.flutter_bluetooth_basic.FlutterBluetoothBasicPlugin.onMethodCall(FlutterBluetoothBasicPlugin.java:113)
E/MethodChannel#flutter_bluetooth_basic/methods(23880): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter_bluetooth_basic/methods(23880): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_bluetooth_basic/methods(23880): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#flutter_bluetooth_basic/methods(23880): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_bluetooth_basic/methods(23880): 	at android.os.MessageQueue.next(MessageQueue.java:330)
E/MethodChannel#flutter_bluetooth_basic/methods(23880): 	at android.os.Looper.loop(Looper.java:169)
E/MethodChannel#flutter_bluetooth_basic/methods(23880): 	at android.app.ActivityThread.main(ActivityThread.java:7094)
E/MethodChannel#flutter_bluetooth_basic/methods(23880): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_bluetooth_basic/methods(23880): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
E/MethodChannel#flutter_bluetooth_basic/methods(23880): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
E/flutter (23880): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'void com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager$PrinterReader.cancel()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tablemi.flutter_bluetooth_basic.DeviceConnFactoryManager$PrinterReader.cancel()' on a null object reference
E/flutter (23880): 	at com.tablemi.flutter_bluetooth_basic.FlutterBluetoothBasicPlugin.disconnect(FlutterBluetoothBasicPlugin.java:250)
E/flutter (23880): 	at com.tablemi.flutter_bluetooth_basic.FlutterBluetoothBasicPlugin.onMethodCall(FlutterBluetoothBasicPlugin.java:113)
E/flutter (23880): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (23880): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (23880): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (23880): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (23880): 	at android.os.MessageQueue.next(MessageQueue.java:330)
E/flutter (23880): 	at android.os.Looper.loop(Looper.java:169)
E/flutter (23880): 	at android.app.ActivityThread.main(ActivityThread.java:7094)
E/flutter (23880): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (23880): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
E/flutter (23880): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)

**Comment by MyoMyatAung** [comment]
So do I. I'm finding out now. LOL

**Comment by FulingFan-1** [comment]
Did you solve this issues?

**Comment by drunisa007** [comment]
use bluetooth termal printer
