### ISSUE TITLE
Bad state: Future already completed

### ISSUE THREAD

**Issue by c0c4i** [andrey-ushakov/esc_pos_bluetooth#58]
When I print sometimes I encounter this error
```
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      PrinterBluetoothManager.writeBytes.<anonymous closure>
package:esc_pos_bluetooth/src/printer_bluetooth_manager.dart:138
#2      _rootRunUnary (dart:async/zone.dart:1198:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#7      Future._complete (dart:async/future_impl.dart:519:7)
#8      new Future.delayed.<anonymous closure> (dart:async/future.dart:323:16)
#9      _rootRun (dart:async/zone.dart:1182:47)
#10     _CustomZone.run (dart:async/zone.dart:1093:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#13     _rootRun (dart:async/zone.dart:1190:13)
#14     _CustomZone.run (dart:async/zone.dart:1093:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#16     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by flutter-painter** [comment]
dup of https://github.com/andrey-ushakov/esc_pos_bluetooth/issues/51
